name: Build Editor Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build-editor-win:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0
      
    - name: Conan setup and install dependencies
      run: |
        conan profile detect --force
        conan remote add artifactory http://artifactory.matthewcotton.net/artifactory/api/conan/conan-local
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}
        conan install . --build=missing --profile conan/profiles/windows_profile
        conan install . --build=missing --profile conan/profiles/windows_profile -s build_type=Debug
        conan upload "*" -r=artifactory -c
        ./build/generators/conanbuild.bat

    - name: Configure CMake
      run: cmake --preset conan-default

    - name: Build Release
      run: cmake --build --preset conan-release -j

    - name: Build Debug
      run: cmake --build --preset conan-debug -j
