name: Upload Package

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-and-upload:
    if: github.repository == 'instinkt900/moth_editor'
    runs-on: ${{ matrix.os == 'windows' && 'windows-latest' || 'ubuntu-latest' }}
    strategy:
      matrix:
        os: [windows, linux]
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Build package and upload
      run: |
        conan remote add artifactory https://artifactory.matthewcotton.net/artifactory/api/conan/conan-local
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}
        conan create . --profile conan/profiles/${{ matrix.os }}_profile --build=missing -s build_type=${{ matrix.build_type }}
        conan upload moth_ui_editor --confirm --remote artifactory

  tag-package:
    if: github.repository == 'instinkt900/moth_editor'
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Fetch package version
        id: get-version
        run: |
          echo "version=$(conan inspect . -f json | jq -r .version)" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.get-version.outputs.version }}
          tag_exists_error: false
          force_push_tag: true
